from project.astronaut.biologist import Biologist
from project.astronaut.geodesist import Geodesist
from project.astronaut.meteorologist import Meteorologist
from project.planet.planet import Planet
from project.space_station import SpaceStation
#
# biologist = Biologist("pesho")
# geodesist = Geodesist("gosho")
# meteorologist = Meteorologist('maria')
# astronaut_repository = AstronautRepository()
# astronaut_repository.add(biologist)
# astronaut_repository.add(geodesist)
# astronaut_repository.add(meteorologist)
# astronaut_repository.remove(biologist)
# planet = Planet('earth', ['something1', 'something2', 'something3', 'something4'])
# planet_repo = PlanetRepository(planet)
# space_station = SpaceStation()
# space_station.add_planet('earth', "'something1', 'something2', 'something3', 'something4'")
# space_station.add_astronaut('Biologist', "pesho")
# space_station.add_astronaut('Biologist', "gosho")
# space_station.add_astronaut('Geodesist', "pesho")
# space_station.add_astronaut('Meteorologist', "pesho")
# print(space_station.astronaut_repository[0].oxygen)
# space_station.recharge_oxygen()
# print(space_station.astronaut_repository[0].oxygen)
#
# print(space_station.send_on_mission('earth'))
# print(space_station.astronaut_repository[0].name)
# print(space_station.report())
# print(space_station.retire_astronaut('gosho'))
# print(space_station.add_astronaut('Geodesist', "pesho"))
b = Biologist("Mike")
g = Geodesist("Peter")
m = Meteorologist("George")
p = Planet("Mars")
ss = SpaceStation()
print(ss.add_astronaut("Biologist", "Neil"))
print(ss.add_astronaut("Geodesist", "Tom"))
print(ss.add_astronaut("Biologist", "Neil"))
print(ss.add_astronaut("Meteorologist", "Elvis"))
# print(ss.add_astronaut("Meteo", "Elvi"))
print(ss.add_planet("Mars", "water, soil, copper, beer, metals, silicone, a, b, c, d, e, f"))
print(ss.add_planet("Mars", "water, soil, copper, beer"))
print(ss.add_planet("Jupi", "water, soil, copper, beer"))
print(ss.planet_repository.planets[0].items)
ss.recharge_oxygen()
print(ss.astronaut_repository.astronauts[0].oxygen)
print(ss.retire_astronaut("Tom"))
print(ss.add_astronaut("Geodesist", "Tom"))
# print(ss.retire_astronaut("Svetlana"))
# print(ss.send_on_mission("R2D2"))

for _ in range(6):
    ss.astronaut_repository.astronauts[0].breathe()

print(ss.astronaut_repository.astronauts[0].oxygen)
print(ss.astronaut_repository.astronauts[2].oxygen)
ss.astronaut_repository.astronauts[2].breathe()
print(ss.astronaut_repository.astronauts[2].oxygen)
ss.recharge_oxygen()
print(ss.astronaut_repository.astronauts[2].oxygen)
ss.astronaut_repository.astronauts[2].breathe()
ss.astronaut_repository.astronauts[2].breathe()
print(ss.astronaut_repository.astronauts[2].oxygen)
print(ss.report())
print(ss.send_on_mission("Mars"))
print(ss.report())

