from project.controller import Controller

controller = Controller()
print(controller.add_aquarium('FreshwaterAquarium', 'some name'))
print(str(controller.aquariums[0]))
print(controller.feed_fish('some name'))
print(controller.add_fish('some name', 'FreshwaterFish', 'nemo', 'species', 1.99))
print(controller.add_fish('some name', 'FreshwaterF', 'nemo', 'species', 1.99))
print(controller.calculate_value('some name'))
print(controller.feed_fish('some name'))
print(controller.report())
print(controller.add_decoration('Plant'))
print(controller.report())
print(controller.add_decoration('Plant'))
# print(controller.insert_decoration('some name', 'Ornament'))
print(controller.insert_decoration('some name', 'Plant'))
print(controller.add_fish('some name', 'SaltwaterFish', 'Nemo', 'species', 10))
print(controller.calculate_value('some name'))
print(controller.decorations_repository.find_by_type('Plant'))
